name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Move files to deployment directory (if exists)
        run: |
          if [ -d "example" ]; then
            mv example/* .
            rm -rf example
          else
            echo "⚠️ Warning: 'example/' directory not found. Skipping move step."
          fi

      - name: Verify index.html exists
        run: |
          if [ ! -f "index.html" ]; then
            echo "❌ ERROR: index.html not found! Stopping deployment."
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
