name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Move files to deployment directory
        run: |
          mv examples/* .
          rm -rf examples

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
